version: '3'

services:
  mosquitto:
    image: "eclipse-mosquitto"
    container_name: "mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "$PWD/mosquitto.conf:/mosquitto/config/mosquitto.conf"
