version: '3'

services:
  traefik:
    image: "traefik"
    command: "--api --docker --docker.watch"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/traefik/traefik.toml:/etc/traefik/traefik.toml"
    networks:
      - "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik/"
  rest:
    build: 
      context: "./rest"
    image: "mbredel/rest/rest:latest"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/rest/api/v1/"
      - "traefik.port=4567"

networks:
  traefik:
