################################################################
# API and dashboard configuration
################################################################
[api]


################################################################
# Docker backend configuration
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "home"
watch = true
usebindportip = true
